name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    # Étape 3 : Backend - Compilation et tests
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install
        working-directory: ./back

      - name: Run tests and generate coverage report
        run: mvn test jacoco:report
        working-directory: ./back

      - name: Verify backend coverage report
        working-directory: back/target/site/jacoco
        run: ls -l jacoco.xml

      # Étape 4 : Analyse SonarCloud
      - name: SonarCloud Scan
       # uses: SonarSource/sonarcloud-github-action@v4
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: back
          args: >
            -Dsonar.projectKey=romain-25_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
            -Dsonar.organization=romain-25
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=back/src
            -Dsonar.java.binaries=back/target/classes
            -Dsonar.java.test.binaries=back/target/test-classes
            -Dsonar.jacoco.reportPaths=back/target/site/jacoco/jacoco.xml
