name: Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4
        #with:
        #  fetch-depth: 0

      # Étape 2 : Frontend - Installation et tests
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies for frontend
        working-directory: front
        run: npm install

      - name: Run tests for frontend
        working-directory: front
        run:  npm test -- --watch=false --browsers=ChromeHeadless --code-coverage

      - name: Debug frontend coverage directory
        working-directory: front/coverage/bobapp
        run: ls -l

      - name: Verify frontend coverage report
        working-directory: front/coverage/bobapp
        run: ls -l lcov.info

      # Étape 4 : Analyse SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v4
       # uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: front
          args: >
            -Dsonar.projectKey=romain-25_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
            -Dsonar.organization=romain-25
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=front/src
            -Dsonar.exclusions=front/src/node_modules/**,front/src/proxy.config.json,front/src/favicon.ico,Dockerfile
            -Dsonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info

      # Se connecter à Docker Hub avec un jeton d'accès
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./front
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
